# Generated by Django 2.0.7 on 2018-11-12 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={},
        ),
        migrations.AlterModelOptions(
            name='superheroe',
            options={},
        ),
    ]
